name: Extended Test

on:
  schedule:
    - cron: '* * * * *'

jobs:
  extended-test:
    runs-on: ubuntu-latest
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy and run integrated test
        run: sleep 30