name: Extended Test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      repo-token:
        required: true

jobs:
  extended-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: nft-mutex
      - name: Deploy and run integrated test
        run: sleep 30