name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: sleep 5

  integrated-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and run integrated test
        run: sleep 5

  stubbed-nft:
    needs: integrated-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: nft-mutex
      - name: Deploy and run stubbed NFT
        run: sleep 30