name: Main

on:
  workflow_call:
    secrets:
      repo-token:
        required: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.repo-token }}
      - name: Run a one-line script
        run: sleep 15

  integrated-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.repo-token }}
      - name: Deploy and run integrated test
        run: sleep 15

  stubbed-nft:
    needs: integrated-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up mutex
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        with:
          branch: nft-mutex
          repo-token: ${{ secrets.repo-token }}
      - name: Deploy and run stubbed NFT
        run: sleep 30